language: python
install:
  - pip install tox-travis
  - pip install pyflakes
services:
  - redis-server
notifications:
  email:
    recipients:
    - justin@justinholmes.com
    on_success: change
    on_failure: always
before_install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install --upgrade codecov tox pyflakes
script: coverage run --source tiempo runtests.py
after_success:
  - codecov

# The following breaks the deployment of code. As it causes the tox script to not be installed. It's an optimization that would save us a total of 3mins if it worked...
# Caution - no way to invalidate this.  If we remove a dep, we might need to run a build with this block commented out.
# cache:
  # directories:
    # - /home/travis/virtualenv/python2.7/bin
    # - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages
    # - /home/travis/miniconda/lib/python2.7/site-packages
    # - /home/travis/.cache/pip/
